name: ${APP_NAME_HOST}

networks:
  internal:
    name: ${APP_NAME_HOST}_internal
    driver: bridge
    ipam:
      config:
        - subnet: "${APP_NETWORK_POOL}"

volumes:
  habitat-config:
  # SERVICENAME-config:

# secrets:
#   SECRET_NAME:
#     file: ${SECRETS_DIR}/SECRET_NAME


services:

  habitat-config-trail:
    image: tschebbischeff/habitat-config:latest
    container_name: ${APP_NAME_HOST}_habitat-config-trail
    restart: no
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/habitat-config.env
        required: false
    environment:
      MODULE_NAME: "trail"
    networks:
      internal:
    volumes:
      - habitat-config:/habitat-config/orchestration
      - ./habitat-config:/habitat-config/source:ro
      # - SERVICENAME-config:/habitat-config/target/SERVICENAME

  SERVICENAME:
    image: alpine:latest
    # build:
    #   context: ./SERVICENAME
    container_name: ${APP_NAME_HOST}_SERVICENAME
    restart: unless-stopped
    # expose:
    #   - '1337'
    env_file:
      - ./.env
      - path: ${ENV_DIR}/.env
        required: false
      - path: ${ENV_DIR}/SERVICENAME.env
        required: false
    environment:
      FOO: 'bar'
    # secrets:
    #   - SECRET_NAME
    # volumes:
    #   - SERVICENAME-config:/DEST/PATH
    networks:
      internal:
    # healthcheck:
    #   test: [ "CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:1337/healthz" ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 10s
    depends_on:
      habitat-config-trail:
        condition: service_completed_successfully
