# Documentation:
# https://doc.traefik.io/traefik/reference/routing-configuration/dynamic-configuration-methods/
# https://doc.traefik.io/traefik/reference/routing-configuration/http/tls/overview/

http:
  services:
    svc_floppy-8000:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: 'http://{{ env "APP_NAME_HOST" }}_floppy:8000'
  routers:
    floppy-8000-pwa:
      rule: 'Host(`{{ env "APP_HOST" }}`) && (PathPrefix(`/static/favicon/`) || PathPrefix(`/static/img/shortcuts/`))'
      service: svc_floppy-8000
      entryPoints: ["websecure"]
      priority: 100
      middlewares:
        - "cors-policy"
      tls:
        certResolver: porkbun-api
    floppy-8000:
      rule: 'Host(`floppy.{{ env "APP_HOST" }}`)'
      priority: 1
      service: svc_floppy-8000
      entryPoints: ["websecure"]
      middlewares:
        - "cors-policy"
        - "auth-proxy"
      tls:
        certResolver: porkbun-api
