# LLM Usage Notice: This file has been generated by Gemini, changes made so far:
# - Renaming Symbols
# - Formatting
# - Implementation of settings derived admin status

from allauth.socialaccount.adapter import DefaultSocialAccountAdapter
from django.contrib.auth.models import Group
from django.conf import settings


class HabitatSocialAccountAdapter(DefaultSocialAccountAdapter):

    def _sync_oidc(self, user, sociallogin):
        extra_data = sociallogin.account.extra_data or {}
        oidc_groups = (
            extra_data.get("groups")
            or extra_data.get("roles")
            or (extra_data.get("realm_access") or {}).get("roles")
            or []
        )
        if not isinstance(oidc_groups, (list, tuple)):
            oidc_groups = []
        admin_groups = getattr(settings, "OIDC_ADMIN_GROUPS", [])
        target_groups = []
        is_admin = False
        for group_name in oidc_groups:
            if not isinstance(group_name, str):
                continue
            group, _ = Group.objects.get_or_create(name=group_name)
            target_groups.append(group)
            if group_name in admin_groups:
                is_admin = True
        print("******************************")
        print(f"{extra_data=}")
        print(f"{oidc_groups=}")
        print(f"{admin_groups=}")
        print(f"{target_groups=}")
        print("******************************")
        user.is_staff = is_admin
        user.is_superuser = is_admin
        user.save(update_fields=["is_staff", "is_superuser"])
        user.groups.set(target_groups)

    def pre_social_login(self, request, sociallogin, **kwargs):
        super().pre_social_login(request, sociallogin, **kwargs)
        if sociallogin.is_existing and sociallogin.user.pk:
            self._sync_oidc(sociallogin.user, sociallogin)

    def save_user(self, request, sociallogin, form=None):
        user = super().save_user(request, sociallogin, form=form)
        self._sync_oidc(user, sociallogin)
        return user
